### PR TITLE
Releases v2.3.4

### PR DESCRIPTION
**Pull request by apandada1**
@LordAmit  From this, create a new branch `alpha`, and make your changes there. By the way, you could also make the pull request yourself. 
To do so, go to pull request in your repository, and you can choose to make a pool from my fork (or any of the forks) to your repo.

### CODE REVIEW

**Comment by LordAmit** [comment]
@apandada1 thanks, and gotcha! 
alpha is up, check! :ghost:

**Comment by LordAmit** [comment]
```/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:141: SyntaxWarning: 's
tr' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:145: SyntaxWarning: 's
tr' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:149: SyntaxWarning: 's
tr' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:232: SyntaxWarning: 's
tr' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
Setting up python3-psutil (5.5.1-1ubuntu4) ...
Setting up brightness-controller (2.3.4-0~202004250741~ubuntu20.04.1) ...
  File "/usr/share/brightness-controller/util/write_config.py", line 21
    def _default_config(config, display_type: str = 'primary'):
```

I believe this is the entire issue. So..dpkg can not process the typehint `str`.

Awkward.

**Comment by LordAmit** [comment]
https://github.com/urwid/urwid/issues/406
looks like my hunch was right. urwid has backward compatibility with python2, and has support for Python3.4 upwards.

Type hint was introduced at later versions of python (3.5+) if I remember correctly, so I guess urwid won't have the python3 type hint support.

**Comment by apandada1** [comment]
Packages are being built and should be ready by half an hour. https://code.launchpad.net/~apandada1/+archive/ubuntu/brightness-alpha
I will also check whether it works.

**Comment by apandada1** [comment]
Looks like alpha ppa is ready.

**Comment by apandada1** [comment]
@LordAmit The alpha version works without issue. Please double check in your machine, and make the same changes to releases and master branch. I will then copy this to the main ppa.

**Comment by LordAmit** [comment]
should work anywhere. I just removed type-hint, after all.

**Comment by LordAmit** [comment]
yup, done.

**Comment by LordAmit** [comment]
@apandada1 let me know if anything needs to be done from my side

**Comment by apandada1** [comment]
I have uploaded it to the ppa https://launchpad.net/~apandada1/+archive/ubuntu/brightness-controller. Looks like things are fine.

**Pull request merged**
