### PR TITLE
Use QtPy the Qt for Python abstraction layer

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
PySide2 and PyQt5 are basically the same thing, and some distro's only have the one or the other packaged. Luckily, [QtPy](https://github.com/spyder-ide/qtpy) exists, which is an abstraction layer for both. This removes the need for users to have both PySide2 and PyQt5 installed to their systems when they want to use multiple Qt-Python applications which might otherwise directly depend on PyQt5 and/or PySide2.

QtPy is almost always a drop in replacement, (at least it was in this case), I tested this on a Gentoo system which has QtPy and PyQt5 installed and found that it works just fine. Someone should test this with PySide2, but I don't expect any problems. It is possible to control which Qt4Python implementation is used with the `QT_API` environment variable.

### CODE REVIEW

**Comment by LordAmit** [comment]
Oh Wow!  Thank you for the contribution @AndrewAmmerlaan.
Did not know about QtPy, and it looks fascinating. I will test it to see how it fairs specially in a new vanilla system and get back to you. 👯‍♂️ 

@apandada1 - if you can, please test it at your end as well. The more we test, the better!

**Comment by apandada1** [comment]
For some reason, KDE Neon's (my primary OS) apt repo does not have a working version of PySide2, for which I could not use the PPA version in it (== no native theming support) in KDE Neon. I had to install PySide2 from pip, which does not support kvantum themes.
But QtPy is there as an `apt` package in KDE Neon, and code in the pull request works. Native themes work too.
Screenshot_20210125_234842


I will be busy this week. I will test it extensively in different DEs and operating systems in the weekend.

**Comment by AndrewAmmerlaan** [comment]
> For some reason, KDE Neon's (my primary OS) apt repo does not have a working version of PySide2, for which I could not use the PPA version in it (== no native theming support) in KDE Neon. I had to install PySide2 from pip, which does not support kvantum themes.

I have similar issues with PySide2 (which is why I opened this PR in the first place :P). Gentoo has support for PySide2 but only through a third party repository, PyQt5 on the other hand is in the main repo. In fact, whenever I run into an application that requires PySide2, I usually just port it to QtPy instead of going through the trouble of installing PySide2. Usually a simple find and sed replacing "PySide2" with "QtPy" is enough.

> But QtPy is there as an `apt` package in KDE Neon, and code in the pull request works. Native themes work too.

In this case QtPy will have used PyQt5 as the back-end (it is the default if both PySide2 and PyQt5 are installed and `QT_API` is not specified.) To launch the application with PySide2, just run `QT_API="pyside2" ./init.py`.

**Comment by apandada1** [comment]
Tested in Manjaro XFCE. Needed to install the dependency `python-qtpy`. There was no need to install PySide. It automatically worked with PyQt5, which was installed in the system.

I did not notice any issue. I guess it can be safely merged.

**Comment by notgernot** [comment]
> For some reason, KDE Neon's (my primary OS) apt repo does not have a working version of PySide2, for which I could not use the PPA version (== no native theming support) in KDE Neon. I had to install PySide2 from pip, which does not support kvantum themes.
> But QtPy is present there as an `apt` package in KDE Neon, and code in the pull request works. Native themes work too.
> Screenshot_20210125_234842
> 
> I will be busy this week. I will test it extensively in different DEs and operating systems in the weekend.


Hi, sorry for some really "noobish" question.
I have some very basic linux knowledge and use KDE NEO (changed from Kubuntu a while ago)
in kubuntu 20.04 the brightness-controller was working perfect without much tweaking.
in KDE NEO i have the dependencie Problems
```
 brightness-controller : Hängt ab von: python3-pyside2.qtcore soll aber nicht installiert werden
                         Hängt ab von: python3-pyside2.qtgui soll aber nicht installiert werden
                         Hängt ab von: python3-pyside2.qtwidgets soll aber nicht installiert werden
                         Hängt ab von: python3-pyside2.qtnetwork soll aber nicht installiert werden
```

Could you please just quickly tell me how you got the brightness controller to work in KDE NEO .
if you have the Tome a patience in some Terminal commands

greets and thanks
notger

**Comment by AndrewAmmerlaan** [comment]
> Hi, sorry for some really "noobish" question.
> I have some very basic linux knowledge and use KDE NEO (changed from Kubuntu a while ago)
> in kubuntu 20.04 the brightness-controller was working perfect without much tweaking.
> in KDE NEO i have the dependencie Problems
> 
> ```
>  brightness-controller : Hängt ab von: python3-pyside2.qtcore soll aber nicht installiert werden
>                          Hängt ab von: python3-pyside2.qtgui soll aber nicht installiert werden
>                          Hängt ab von: python3-pyside2.qtwidgets soll aber nicht installiert werden
>                          Hängt ab von: python3-pyside2.qtnetwork soll aber nicht installiert werden
> ```
> 
> Could you please just quickly tell me how you got the brightness controller to work in KDE NEO .
> if you have the Tome a patience in some Terminal commands
> 
> greets and thanks
> notger

```
pip install --user PySide2
```

Or apply the patch from this PR to the code, in which case it will be able to run with both PyQt5 and PySide2. Which means that it will probably work out of the box, and if not `apt-get install QtPy` should do the trick.

**Comment by apandada1** [comment]
I have updated the PPA with this dependency. I have tested it in two computers running Ubuntu 20.04 and derivatives, but just in case there is an issue with the update, please report here.

**Comment by LordAmit** [comment]
You are the best, @apandada1  😄

**Pull request merged**
