### PR TITLE
A system tray icon has been added

### PR DESCRIPTION
**Pull request by shivams**
Tray icon has been added. This helps in keeping the app running in the background so that the settings aren't lost.

### CODE REVIEW

**Comment by auvipy** [comment]
@lordamit This pull request can be automatically merged by project collaborators. So if you have time :)

**Comment by apandada1** [comment]
We are contributors, but not collaborators (we do not have any write acces to this repo). So we can do nothing. I have one question. 
This tray icon keeps the settings when the app is closed or minimized, but we cannot keep the settings after a reboot.
@lordamit  So, is there a way we can automatically export the settings to the users home folder (in a hidden file) when the app is going to be closed and import them when we start the app?

**Comment by lordamit** [comment]
Hello all,
I have checked the pull request. It is good, but it needs to solve the following problems: 

@shivams 

- the icon for a minimized brightness controller is a heart icon, which is not relevant. 
- at present, the size of the brightness controller is fixed, hence the option maximize from the system tray menu is not relevant 

@auvipy  - sure, but really don't have the time to fix the issues it will create once pulled :ghost: 

@apandada1  - that can certainly be done. :smile: Want to give it a try?

**Comment by apandada1** [comment]
@lordamit I will try. If I cannot do within 15 days, I will let you know.

**Pull request closed without merging**
