### PR TITLE
It was updated to 1.2.3

### PR DESCRIPTION
**Pull request by apandada1**
Version number for simple is now 1.2.3

### CODE REVIEW

**Comment by xSeekTruthx** [comment]
Also needs to be changed in v1 branch. Also, you mint screen shots show some off positioning for Not Found on Fourth. Here is a screen shot in Ubuntu 14.04 LTS.
image

**Comment by xSeekTruthx** [comment]
@apandada1 the PPA packages here https://launchpad.net/~apandada1/+archive/ubuntu/brightness-controller/+packages say Third Monitor Support on the change log. Not sure if you meant that to say 4 monitor support.

**Comment by apandada1** [comment]
Updating changelog will need to change the version number. I did not know about the 4th monitor support at that time. Should I leave it?

**Comment by xSeekTruthx** [comment]
Idk what protocol is for this. It doesn't matter to me.

**Comment by apandada1** [comment]
It means I will have to push a whole update (without any new features) and change the version number to change the changelog. So my suggestion is, leave it for now. It can be done later when some features are added.

**Comment by xSeekTruthx** [comment]
Hey Guys, I'm trying to implement a ".focus()" to the primary scroll bar
when brightness-controller-simple runs.

I've tried slider1.focus(), hbox1.focus(), primary_scroll.focus() and
self.primary_scroll.focus() in various places inside the python code.
Nothing seems to highlight the first horizontal scroll as soon as it loads
without having to do a manual mouse click. Any chance someone could tell me
how or when to implement this for myself?

Thank you and hope you all are doing well!

**Pull request merged**
