### PR TITLE
Default saving and loading on start up with GUI dropdown options, prep for systemtray

### PR DESCRIPTION
**Pull request by jahan-addison**
* Default saving and loading on start up with options
* Creation of default file location in ~/.config
* Save temperature along with brightness settings
* Preparation for minimize to system tray

`Clear default settings` option is hidden until a set of defaults have been saved.

selection_013

### CODE REVIEW

**Comment by apandada1** [comment]
Great!!
I checked that this works. I have only one monitor. So I don't know whether the following issue (related to this) might turn up.

Suppose the user saves settings when an external monitor is attached, and then opens the app again after detaching the external monitor. Is the app stable in such cases? 
We would want it to still load saved settings for the primary monitor. It is still fine if it cannot load the settings correctly, but it must not crash.
Can anybody check this?

**Comment by jahan-addison** [comment]
I can check and see what happens. I built these changes with 2 monitors so I can verify both

**Comment by jahan-addison** [comment]
@apandada1 After testing with my monitors, with or without my new changes, it seems loading settings initially for 2 monitors into 1 will only apply the primary settings, and the secondary widgets become disabled. Reattaching my monitor and then loading the controller again seems to apply to both as expected.

I wonder, though, maybe we want a simplified GUI for when there's only 1 monitor? Something to think about.

**Comment by LordAmit** [comment]
Hey, thanks for the modifications!
Looks good.  I still have to check a few things though. My hands are full till 21th December.  So please wait till then - can not wait to merge it! :man_dancing:

**Comment by apandada1** [comment]
I am in a trip. I will upload it to the PPA in the first week of January.

**Comment by LordAmit** [comment]
Take your time, gives us more time to test :smile: 
@jahan-addison Thanks for the hard work, looking forward to the systray.  :man_dancing:

**Pull request merged**
