### PR TITLE
Feature: Close to systemtray - verify quit

### PR DESCRIPTION
**Pull request by jahan-addison**
Happy new Years!!!! :tada::balloon::fireworks: Getting this finished was easier than I thought!

**Note**: In order for the tray to appear with Qt4, I needed to install `sni-qt` (via `apt install sni-qt`)

I have a couple questions, though:

* Would we want an option to always start minimized? (I personally autostart this tool on my machine on start up anyway)
* Are these logistics OK? I thought about verifying you want to quit before it goes to tray, but not too many other apps do it this way.

Preview: gif

### CODE REVIEW

**Comment by LordAmit** [comment]
Nice!

I believe we can offer both 

-To quit when clicked on close
- Start minimized when started

through prefereneces. Check boxes which will be saved in settings under config should be easy to do. :smile:

**Comment by apandada1** [comment]
Now that it runs in the tray, can we implement hotkeys (Issue #34)?

**Comment by apandada1** [comment]
I will upload to the PPA once point 4 (in above comment) is sorted out. The other three can be gradually implemented.

**Comment by LordAmit** [comment]
The issue 3 you mentioned is a problem of implementing singleton pattern. 
Good catch about the bug. @jahan-addison  - please look into this asap.

**Pull request merged**
